language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - jruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
env:
  - SLOW_SPEC=true
  - SLOW_SPEC=false
script: 'bundle exec rake spec'
before_script: 'gem install bundler'